export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOG_OUT = "LOG_OUT";

export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_LOADING = "SIGNUP_LOADING";

export const GET_PROFILE_USER = "GET_PROFILE_USER";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";

export const GET_ITEMS_USER = "GET_ITEMS_USER";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";
export const GET_ITEMS_LOADING = "GET_ITEMS_LOADING";

export const GET_CUSTOMERS_USER = "GET_CUSTOMERS_USER";
export const GET_CUSTOMERS_FAILED = "GET_CUSTOMERS_FAILED";
export const GET_CUSTOMERS_LOADING = "GET_CUSTOMERS_LOADING";

export const GET_ANALYTICS_USER = "GET_ANALYTICS_USER";
export const GET_ANALYTICS_FAILED = "GET_ANALYTICS_FAILED";
export const GET_ANALYTICS_LOADING = "GET_ANALYTICS_LOADING";